version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
        - ./front:/app

  sheduler:
    build:
      context: ./sheduler
      dockerfile: Dockerfile
    restart: always
    volumes:
        - ./sheduler:/app

  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          if [ "$(date +'%H:%M')" = '00:00' ]; then
            docker restart frontend
          fi
          sleep 60
        done

  # web:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.prod
  #   command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
  #   volumes:
  #     - ./app:/usr/src/app
  #   ports:
  #     - 8004:8000
    # environment:
    #   - ENVIRONMENT=dev
    #   - TESTING=0
    #   - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
    #   - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    # depends_on:
    #   - web-db

  # web-db:
  #   build:
  #     context: ./app/db
  #     dockerfile: Dockerfile
  #   expose:
  #     - 5432
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
